### ISSUE TITLE
ckeditor save disable ??

### ISSUE THREAD

**Issue by mareban** [gilvanleal/odoowidgets#9]
Hello,

I've installed your ckeditor module in Odoo 10, and modify the document management system view to use it ! It works great, except that the save button is disbaled !!

If i copy/paste a picture in the document, everything is ok, except that when i try to save the document with the picture, the picture is never saved !!

How can i save document with picture pasted using your ckeditor please ?

Thanks for your help.

Regards.

Picture is embeded with : 

data:image/png;base64,iVBORw0....

**Comment by gilvanleal** [comment]
close
